version: '3.5'

services:
  node_worker:
    image: node:18
    env_file:
      - ./.env
    command: yarn start
    environment:
      - NODE_ENV=production
    working_dir: /app
    volumes:
      - .:/app
    networks:
      - play_nation_net


networks:
  play_nation_net:
